name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
    # Artifact name
        name: programa # optional
    # Destination path
     #   path: main # optional
  
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
       # registry: # optional
        # Username used to log against the Docker registry
         username: juniorvs # optional
        # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.PASSWORD_DOCKER_HUB }} # optional
        # Specifies whether the given registry is ECR (auto, true or false)
     #   ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
      #  logout: # optional, default is true
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
# Build's context is the set of files located in the specified PATH or URL
        context: .
# Path to the Dockerfile
        file: ./Dockerfile
# Push is a shorthand for --output=type=registry
        push: true
# List of tags
        tags: juniorvs/go_ci:${{github.ref_name}}
